### PR TITLE
Fix: trip details carousel button getting stuck

### PR DESCRIPTION
**Pull request by timwangmusic**
## Description
The plan details page carousel did not consider when we have multiple places in a travel plan. There were 3 fixed button in the HTML page. After users click on the last image, the screen will stuck.

## Solution
* Render number of carousel buttons per places in the travel plan
* Use dark variant for the carousel indicators
* Reformat the HTML page source code
* Reformat conditional class assignment such as `<div class={{if index $active $i}} "card-body" {{else}} "card-body d-none" {{end}}>` so that we can do the reformat

## Testing
- [x] Integration testing on Heroku staging
- [ ] Added new unit tests

## Checks
- [x] Have you removed commented code?
- [x] Have you used gofmt to format your code?

### CODE REVIEW

**Review by rwangsc18 — COMMENTED** [review]
Overall LGTM. Thanks for the fix to make carousel to show more than 3 photos!

Since photos from different places may have different height, I am not sure if the fade works well for them. It may create illusion of large latency when transitioning from places.

**Comment by timwangmusic** [comment]
> Overall LGTM. Thanks for the fix to make carousel to show more than 3 photos!
> 
> 
> 
> Since photos from different places may have different height, I am not sure if the fade works well for them. It may create illusion of large latency when transitioning from places. 

Agreed, should we fix the image height or remove the fading effect?

**Comment by rwangsc18** [comment]
> Agreed, should we fix the image height or remove the fading effect?
I would recommend removing the fading effect. Images come in with different height, aligning them with the height will stretch some to a weird height:width ratio.

**Comment by timwangmusic** [comment]
> > Agreed, should we fix the image height or remove the fading effect?
> > I would recommend removing the fading effect. Images come in with different height, aligning them with the height will stretch some to a weird height:width ratio.

Removed the fading effect.

**Review by rwangsc18 — APPROVED** [review]
LGTM

**Pull request merged**
