### PR TITLE
Chore: miscellaneous fixes

### PR DESCRIPTION
**Pull request by timwangmusic**
Thanks GoLand problem detector!

## Description
Miscellaneous fixes for the sloppiness in code base.

### CODE REVIEW

**Review by rwangsc18 — APPROVED** [review]
LGTM.
This is cool. What's the name of the tool?

**Comment by sananand007** [comment]
is this a linter ? @timwangmusic

**Review by sananand007 — APPROVED** [review]
looks like a formatter

**Comment by timwangmusic** [comment]
It's the problem detector in Goland, so good.

**Pull request merged**
