### PR TITLE
[task] Update to go-1.21

### PR DESCRIPTION
**Pull request by sananand007**
## Description
Clearly describe changes in your PR, new feature or bug fixes.

## Solution
* Describe your code changes in detail for reviewers as well as documentation purposes. 
* For bug fixes, explain the solutions and how they fix the issues.
* For new features, describe the high-level ideas.

## Testing
- [ ] Integration testing on Heroku staging
- [ ] Added new unit tests

## Checks
- [ ] Have you removed commented code?
- [ ] Have you used gofmt to format your code?

### CODE REVIEW

**Review by timwangmusic — CHANGES_REQUESTED** [review]
We should not change the module name

**Comment by sananand007** [comment]
its auto @timwangmusic , may be the update sees that is the correct way ?

**Comment by timwangmusic** [comment]
> its auto @timwangmusic , may be the update sees that is the correct way ? 

Can you run to mod tidy?

**Comment by sananand007** [comment]
@timwangmusic `go mod tidy` does not change anything, exactly the same

**Pull request closed without merging**
