### PR TITLE
Feat: show plan details button on user profile page

### PR DESCRIPTION
**Pull request by timwangmusic**
## Description
Add a button to direct users to plan details page for their saved plans.

## Solution
* Use `original_plan_id` field in plan views to construct URL.

## Testing
- [x] Integration testing on Heroku staging
- [ ] Added new unit tests

## Checks
- [x] Have you removed commented code?
- [x] Have you used gofmt to format your code?

### CODE REVIEW

**Review by sananand007 — APPROVED** [review]
lg if you have tested out locally

**Review by rwangsc18 — COMMENTED** [review]
LGTM. Somehow the new button is not shown in the staging app, is it just me or staging app not working properly?
Screen Shot 2023-02-12 at 8 52 03 PM

**Comment by timwangmusic** [comment]
> LGTM. Somehow the new button is not shown in the staging app, is it just me or staging app not working properly? Screen Shot 2023-02-12 at 8 52 03 PM

It's on the test environment, you can check here https://testing-vp.herokuapp.com/

**Comment by rwangsc18** [comment]
> > LGTM. Somehow the new button is not shown in the staging app, is it just me or staging app not working properly? Screen Shot 2023-02-12 at 8 52 03 PM
> 
> It's on the test environment, you can check here https://testing-vp.herokuapp.com/

Thanks, the testing-vp link works. I can see the new button and test its redirection to the details page.
Great feature added to enhance user experience!

**Pull request merged**
